specVersion: 1.0.0
name: nova-governance
version: 0.0.1
runner:
  node:
    name: "@subql/node"
    version: "*"
  query:
    name: "@subql/query"
    version: "*"
description: Project for tracking direct and delegated votings gor OpenGov
repository: "https://github.com/nova-wallet/subquery-governance"
schema:
  file: ./schema.graphql
network:
  chainId: "0xb0a8d493285c2df73290dfb7e61f870f17b41801197a149ca93654499ea3dafe"
  endpoint: "wss://kusama.api.onfinality.io/public-ws"
  dictionary: "https://api.subquery.network/sq/subquery/kusama-dictionary"
dataSources:
  - kind: substrate/Runtime
    startBlock: 17048974
    # first delegation at 15427815 
    # first referendum 15426832
    # 15428109 - batch inside multisig
    # 16662525 - proxy announced
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleReferendumSubmission
          kind: substrate/EventHandler
          filter:
            module: referenda
            method: Submitted

        - handler: handleVoteHandler
          kind: substrate/CallHandler
          filter:
            module: convictionVoting
            method: vote
            success: true

        - handler: handleRemoveVoteHandler
          kind: substrate/CallHandler
          filter:
            module: convictionVoting
            method: removeVote
            success: true

        - handler: handleDelegateHandler
          kind: substrate/CallHandler
          filter:
            module: convictionVoting
            method: delegate
            success: true

        - handler: handleUndelegateHandler
          kind: substrate/CallHandler
          filter:
            module: convictionVoting
            method: undelegate
            success: true

        - handler: handleTerminal
          kind: substrate/EventHandler
          filter:
            module: referenda
            method: Confirmed

        - handler: handleTerminal
          kind: substrate/EventHandler
          filter:
            module: referenda
            method: Rejected

        - handler: handleTerminal
          kind: substrate/EventHandler
          filter:
            module: referenda
            method: Killed

        - handler: handleTerminal
          kind: substrate/EventHandler
          filter:
            module: referenda
            method: Cancelled

        - handler: handleTerminal
          kind: substrate/EventHandler
          filter:
            module: referenda
            method: TimedOut

        - handler: handleNestedCalls
          kind: substrate/CallHandler
          filter:
            module: proxy
            method: proxy
            success: true

        - handler: handleNestedCalls
          kind: substrate/CallHandler
          filter:
            module: proxy
            method: proxyAnnounced
            success: true

        - handler: handleNestedCalls
          kind: substrate/CallHandler
          filter:
            module: utility
            method: batch
            success: true

        - handler: handleNestedCalls
          kind: substrate/CallHandler
          filter:
            module: utility
            method: batchAll
            success: true

        - handler: handleNestedCalls
          kind: substrate/CallHandler
          filter:
            module: utility
            method: forceBatch
            success: true

        - handler: handleNestedCalls
          kind: substrate/CallHandler
          filter:
            module: multisig
            method: asMulti
            success: true

        - handler: handleNestedCalls
          kind: substrate/CallHandler
          filter:
            module: multisig
            method: asMultiThreshold1
            success: true

        - handler: handleNestedCalls
          kind: substrate/CallHandler
          filter:
            module: utility
            method: asDerivative
            success: true
